name: Sync from template
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    # Remove all default token permissions so that GitHub won't provide GITHUB_TOKEN at all.
    # This ensures that the only token we have is your PAT.
  permissions: {}
  env:
    GITHUB_TOKEN: ${{ secrets.PAT_SYNC }}

    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Use your PAT
        # Make sure the *environment variable* GITHUB_TOKEN is your PAT
        run: echo "GITHUB_TOKEN=${{ secrets.PAT_SYNC }}" >> $GITHUB_ENV

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1
        with:
          # Also set the "github_token" input
          github_token: ${{ secrets.PAT_SYNC }}
          source_repo_path: alshedivat/al-folio
          upstream_branch: master
